import { SCHEMA_VERSION, type FormSchema } from "./types/form.js";

/** Minimal example schema for playground and docs. */
export const sampleContactForm: FormSchema = {
  id: "contact-form",
  version: SCHEMA_VERSION,
  title: "Contact us",
  description: "We will get back to you shortly.",
  settings: {
    submitLabel: "Send message",
    cancelLabel: "Cancel",
    successMessage: "Thanks! Your message was sent.",
    mode: "add",
  },
  layout: {
    type: "single",
  },
  fields: [
    {
      id: "field-firstname",
      type: "text",
      name: "firstName",
      label: "First name",
      required: true,
      placeholder: "Jane",
      props: { gridSpan: 6, group: "General" },
    },
    {
      id: "field-lastname",
      type: "text",
      name: "lastName",
      label: "Last name",
      required: true,
      placeholder: "Doe",
      props: { gridSpan: 6, group: "General" },
    },
    {
      id: "field-email",
      type: "email",
      name: "email",
      label: "Email",
      required: true,
      placeholder: "jane@example.com",
      validation: [{ type: "email" }],
      props: { gridSpan: 8, group: "General" },
    },
    {
      id: "field-phone",
      type: "phone",
      name: "phone",
      label: "Phone",
      placeholder: "+1 555 123 4567",
      props: { gridSpan: 4, group: "General" },
    },
    {
      id: "field-rating",
      type: "rating",
      name: "satisfaction",
      label: "How satisfied are you?",
      max: 5,
      props: { gridSpan: 6, group: "Feedback" },
    },
    {
      id: "field-priority",
      type: "slider",
      name: "priority",
      label: "Priority",
      min: 0,
      max: 10,
      step: 1,
      defaultValue: 5,
      props: { gridSpan: 6, group: "Feedback" },
    },
    {
      id: "field-message",
      type: "textarea",
      name: "message",
      label: "Message",
      rows: 4,
      required: true,
      props: { gridSpan: 12, group: "Feedback" },
    },
  ],
};
